django/myblog/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # （正则）所有地址
    # url(r'^', views.blog),
    url(r'^index/$', views.index, name='index'),
    # url(r'^article/(?P<article_id>[0-9]+)/$', views.article_page),
    url(r'^article/(?P<article_id>[0-9]+)/$', views.article_page, name='article_page'),

    # add edit
    # url(r'^edit/$', views.edit_page, name='edit_page'),

    # add edit article_id
    url(r'^edit/(?P<article_id>[0-9]+)/$', views.edit_page, name='edit_page'),
    url(r'^edit/action$', views.edit_action, name='edit_action')
]

django/myblog/myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

"""
注意 这使用于2.7
"""

# import blog.views as bv

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^blog/', bv.blog),
    # url(r'^blog/', include('blog.urls'))
    url(r'^blog/', include('blog.urls', namespace='blog'))
]

django/myblog/blog/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)

    # add time -- auto_now=True
    pub_time = models.DateTimeField(null=True)

    # __unicode__
    def __str__(self):
        return self.title

django/myblog/blog/views.py
from django.shortcuts import render

from django.http import HttpResponse
from . import models


def index(request):
    # return HttpResponse("hello Django")

    # return render(request, 'blog/blog.html' )

    # 获取一条
    # article = models.Article.objects.get(pk=1)
    # return render(request, 'blog/index.html', {'article': article})

    # 获取所有
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles':articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article':article})


def edit_page(request, article_id):

    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article':article })




def edit_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    article_id = request.POST.get('article_id', '0')

    if article_id == '0':
        """ 添加 """
        models.Article.objects.create(title=title, content=content)
        # 返回首页，显示全部
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles':articles})

    """ 修改 """
    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request, 'blog/article_page.html', {'article': article})

django/myblog/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
<h1>{{article.title}}</h1>
<h3>{{article.content}}</h3>
<h4><a href="{% url 'blog:index' %}">回到首页</a></h4>
<h4><a href="{% url 'blog:edit_page' article.id %}">修改文章</a></h4>
</body>
</html>

django/myblog/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
</head>
<body>
<div class="box">
    <form action="{% url 'blog:edit_action' %}" method="post">
        {% csrf_token %}

        <!-- modify ---
        {% if article %}

            <input type="hidden" name="article_id" value="{{article.id}}">
            <div>
                <label for="">title</label>
                <input type="text" name="title" value="{{article.title}}">
            </div>

            <div>
                <label for="">content</label>
                <input type="text" name="content" value="{{article.content}}">
            </div>
        -->
        <!-- add ---
        {% else %}
            <input type="hidden" name="article_id" value="0">
            <div>
                <label for="">title</label>
                <input type="text" name="title">
            </div>

            <div>
                <label for="">content</label>
                <input type="text" name="content">
            </div>
        {% endif %}
        -->

        <!-- 过滤器 -->
        <input type="hidden" name="article_id" value="{{article.id | default:'0' }}">
        <div>
            <label for="">title</label>
            <input type="text" name="title" value="{{article.title}}">
        </div>

        <div>
            <label for="">content</label>
            <input type="text" name="content" value="{{article.content}}">
        </div>

        <input type="submit" value="提 交">
    </form>
</div>


</body>
</html>

django/myblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
    <h1>hello django</h1>
    <h3><a href="{% url 'blog:edit_page' 0 %}">Add Article</a></h3>
    <ul>
        {% for article in articles %}
        <li><a href="{% url 'blog:article_page' article.id %}">{{article.title}}</a></li>
        {% endfor %}
    </ul>
</body>
</html>